#!/bin/sh

# Based on http://forums.indigodomo.com/viewtopic.php?t=10704&f=22

# This is for sending apcupsd events to a running Indigo server for triggering purposes.
#
# From any of the apcupsd scripts in /etc/apcupsd (such as "offbattery"), include a line like this:
#
#	source /etc/apcupsd/tell_indigo $(basename $0) "$1" "$2" "$3"
#
# Note: This script currently only uses the first two parameters: event name and UPS name
#
# We will be sending the event to an Indigo server that is running the apcupsd plugin. Here's where
# we try to get in touch:

INDIGO_SERVER=127.0.0.1
INDIGO_PORT=15006

EVENT=$1
UPS=$2

# as needed, change the UPS name into something that matches Indigo's device
case ${UPS} in
	# here we match based on the exact UPS name being passed to us by the apcupsd config
	"" | test | test-UPS | test.local ) {
		# This is the device name of the matching device in Indigo
		UPS="test UPS"
		# or use the Device Id (preferred)
		UPS=123456789
		};;
	test2 ) {
		UPS=987654321
		};;
esac

/bin/echo -n "${UPS}:${EVENT}" | /usr/bin/nc -w1 "${INDIGO_SERVER}" "${INDIGO_PORT}" &
