#!/bin/sh

# Based on http://forums.indigodomo.com/viewtopic.php?t=10704&f=22

# This is for sending apcupsd events to a running Indigo server for triggering purposes.
#
# From any of the apcupsd scripts in /etc/apcupsd (such as "offbattery"), include a line like this:
#
#	. /etc/apcupsd/tell_indigo
#
# We will be sending the event to an Indigo server that is running the apcupsd plugin. Here's where
# we try to get in touch:

INDIGO_SERVER=127.0.0.1
INDIGO_PORT=15006

EVENT=$1
UPS=$2

case ${UPS} in
	# here we match based on the exact UPS name being passed to us by the apcupsd config
	"" | test | test-UPS | test.local ) {
		# This is the device name of the matching apcupsd device in Indigo
		UPS="test UPS"
		# or if you'd prefer, use the Device Id
		UPS=123456789
		};;
esac

/bin/echo -n "${UPS}:${EVENT}" |/usr/bin/nc -w1 "${INDIGO_SERVER}" "${INDIGO_PORT}" &
