#!/bin/bash
#
# This script will perform any conversion steps needed to make this plugin work
# with Indigo 5, including to support Indigo 5's older version of Python.
#
# It should only need to be used once per upgrade of the plugin.

CODE_PATH="/Library/Application Support/Perceptive Automation/Indigo 5/Plugins (Disabled)/apcupsd.indigoPlugin/Contents/Server Plugin/"
if [ "$1" != "" ]; then CODE_PATH=$1 ; fi

# Announce ourselves...

echo
echo "		Starting `basename $0`"
echo

# Make sure the plugin is Disabled before anything else

if [ ! -d "$CODE_PATH" ]; then
	echo "No such path:"
	echo "    $CODE_PATH"
	echo
	echo "The plugin does not appear to be in the Disabled state!"
	echo
	echo "Using the Indigo client, select the 'Plugins --> apcupsd --> Disable' menu"
	echo "option and then re-run this script."
	echo
	echo "No changes made."
	echo
	exit 1
fi

# Now ready to make changes

echo "		Making Python-related changes"

(cd "$CODE_PATH" ; sed -e "s/\(.except .*\)\( as \)\(.*:\)$/\1, \3/" -i .2.6 *.py)

echo
echo "		Completed `basename $0`"
echo
